### ISSUE TITLE
Concludere i TODO attuali nel codice

### ISSUE THREAD

**Issue by cathartyc** [AFLdiscord/AFL-Bot#64]
Nel codice sono presenti dei TODO che andrebbero valutati e risolti.
# TODO
### [events_cog.py](https://github.com/AFLdiscord/AFL-Bot/blob/master/cogs/events_cog.py):
- [x] Accorciare `on_message`
- [x] Migliorare accesso ad afler in `on_message`
- [x] Impostare l'avvio del task a mezzanotte indipendentemente da quando è stato avviato il bot
- [x] Accorciare `periodic_checks`
### [afler.py](https://github.com/AFLdiscord/AFL-Bot/blob/master/utils/afler.py):
- [x] Valutare di snellire il dizionario
### [proposals.py](https://github.com/AFLdiscord/AFL-Bot/blob/master/utils/proposals.py):
- [x] Spostare durata della proposta nella configurazione

**Comment by cathartyc** [comment]
Il dizionario AFL non è accorciabile perché contiene già il numero minimo di informazioni indispensabili. Tuttavia #69 è stata aperta per semplificarne l'accesso.
